spring:
  application:
    name: Todo

  datasource:
    url: jdbc:mysql://todo-mysql:3306/TodoApp?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: redis_cache
      port: 6379

server:
  servlet:
    context-path: /api/v1
  port: 8000